---
### HOMEWORK --> make a notebook and read all different format files.
---

**All DATASET that are used in this notebook are available on the GitHub repository. link: "https://github.com/pandas-dev/pandas/tree/main/pandas/tests/io/data"** 

### List of Different format that are implemented here 
1. .csv
2. .json
3. .xml
4. .excel
5. .html
6. pickle
7. tar
8. orc

In [ ]:
import pandas as pd

In [ ]:
## Reading the .csv file

csv_f = pd.read_csv("./IPL2025Batters.csv")
csv_f.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

In [ ]:
# Reading .json files

json_f = pd.read_json("./airports.json")
json_f.head()

                                            airports
0  {'code': 'ATL', 'name': 'Hartsfield-Jackson At...
1  {'code': 'PEK', 'name': 'Beijing Capital Inter...
2  {'code': 'DXB', 'name': 'Dubai International',...
3  {'code': 'LAX', 'name': 'Los Angeles Internati...
4  {'code': 'HND', 'name': 'Tokyo Haneda', 'city'...

In [ ]:
# Reading .xml files

xml_f = pd.read_xml("./books.xml")
xml_f.head()

   category             title               author  year  price
0   cooking  Everyday Italian  Giada De Laurentiis  2005  30.00
1  children      Harry Potter         J K. Rowling  2005  29.99
2       web      Learning XML          Erik T. Ray  2003  39.95

In [ ]:
# Reading Excel files (.xlsm, .xls, .xlsx, .ods)

excel_f = pd.read_excel("./blank.xlsm")
print(excel_f)

Empty DataFrame
Columns: []
Index: []

In [ ]:
# Reading .html files

html_f = pd.read_html("./banklist.html")
print(html_f)

[                                  Bank Name           City  ST   CERT  \
0  Banks of Wisconsin d/b/a Bank of Kenosha        Kenosha  WI  35386
1                      Central Arizona Bank     Scottsdale  AZ  34527
2                              Sunrise Bank       Valdosta  GA  58185
3                     Pisgah Community Bank      Asheville  NC  58701
4                       Douglas County Bank   Douglasville  GA  21649
5                              Parkway Bank         Lenoir  NC  57158
6                    Chipola Community Bank       Marianna  FL  58034
7                            Heartland Bank        Leawood  KS   1361
8                           Waterfield Bank     Germantown  MD  34976
9                    Waterford Village Bank  Williamsville  NY  58065

              Acquiring Institution    Closing Date       Updated Date
0             North Shore Bank, FSB    May 31, 2013       May 31, 2013
1                Western State Bank    May 14, 2013       May 20, 2013
2                      Synovus Bank    May 10, 2013       May 21, 2013
3                Capital Bank, N.A.    May 10, 2013       May 14, 2013
4               Hamilton State Bank  April 26, 2013       May 16, 2013
5  CertusBank, National Association  April 26, 2013       May 17, 2013
6     First Federal Bank of Florida  April 19, 2013       May 16, 2013
7                      Metcalf Bank   July 20, 2012  December 17, 2012
8                       No Acquirer   March 5, 2010    August 23, 2012
9                  Evans Bank, N.A.   July 24, 2009    August 20, 2012  ]

In [ ]:
# Reading .pickle files

pickle_f = pd.read_pickle("./categorical.0.25.0.pickle")
print(pickle_f)

['a', 'b', 'c', 'd']
Categories (4, object): ['a', 'b', 'c', 'd']

In [ ]:
# Reading .tar files


tar_f = pd.read_csv("./test-csv.tar")
print(tar_f)

   1;2
0  3;4

In [ ]:
# Reading .orc files

orc_f = pd.read_orc("./TestOrcFile.decimal.orc")
print(orc_f)

            _col0
0     -1000.50000
1      -999.60000
2      -998.70000
3      -997.80000
4      -996.90000
...           ...
5995   1995.19960
5996   1996.19970
5997   1997.19980
5998   1998.19990
5999   1999.20000

[6000 rows x 1 columns]